import { APP_NAVIGATION_ITEMS } from './AppNavigation.types'

export const MENU_ITEMS: APP_NAVIGATION_ITEMS[] = [
  APP_NAVIGATION_ITEMS.HOME,
  APP_NAVIGATION_ITEMS.SHOP,
  APP_NAVIGATION_ITEMS.ACCOUNT,
  APP_NAVIGATION_ITEMS.PAGES,
  APP_NAVIGATION_ITEMS.BLOG,
  APP_NAVIGATION_ITEMS.DOCS
] as const
